name: dask-tutorial
channels:
  - conda-forge
dependencies:
  - python=3.7
  - bokeh=2.0  # Pinned until distributed 2.19 release due to breaking change
  - dask
  - dask-ml
  - jupyterlab
  - ipykernel
  - nodejs
  - tornado
  - numba
  - numpy
  - pip
  - pandas
  - pyarrow
  - python-graphviz
  - seaborn
  - scikit-learn
  - matplotlib
  - nbserverproxy
  - nomkl
  - h5py
  - xarray
  - requests
  - pytables
  - pip:
    - mimesis
    - dask_labextension  
  
